### ISSUE TITLE
slider section and logos sections doesn't work as i wanted them to,

### ISSUE THREAD

**Issue by Daryan98** [ticketbutler/homepage#9]
we should change the config yml, because we should have those two new sections inside others so our marketing people can add more then one of those section and place it where ever they want.

**Comment by kjkta** [comment]
I think it isn't possible to have different object types in a list.

So I think your options are:
1. Create a collection for each component type. fx. Create a collection "Component  - Hero" then create an entry called "Front page hero", then in your "Page" collection the list just has a relation field in the list (https://www.netlifycms.org/docs/widgets/#relation).
2. Find a different CMS!

Let me know what you think. Feel free to try both solutions!

**Comment by Daryan98** [comment]
ok, I will try them both and see which one works best 👍
